default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

  #Dockerにもどしたら以下を有効に
  # adapter: mysql2
  # encoding: utf8
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # database: Portfolio_yagishita_test
  # username: root
  # password: password
  # host: localhost
  # socket: /var/lib/mysql/mysql.sock

test:
  <<: *default
  database: Portfolio_yagishita_test


production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>